#!/bin/bash

WORKINGDIR=$HOME/GM2/gcc-git

if [ -d ${WORKINGDIR} ] ; then
    cd ${WORKINGDIR}

    echo "creating fresh gm2 git, this is the inc reprository"

    rm -rf gm2
    tar xf gm2.tar

    echo "creating fresh gcc git, this is the des reprository"

    rm -rf gcc
    tar xf gcc.tar

    echo "creating patch scripts and combining: des += inc"

    rm -rf patch-scripts patch-scripts-9.2.0
    rm -rf patch-scripts-8.2.0 patch-scripts-6.4.0
    python3 combine.py -f gcc+gm2-master.comb
    python3 combine.py -f gcc+gm2-9.2.0.comb
    python3 combine.py -f gcc+gm2-8.2.0.comb
    python3 combine.py -f gcc+gm2-6.4.0.comb
else
    echo "${WORKINGDIR} does not exist"
    exit 1    
fi

