#!/bin/bash

cd $HOME/GM2/gcc-git

echo "creating fresh gm2 git"
rm -rf gm2
tar xf gm2.tar

echo "creating fresh gcc git"
rm -rf gcc
tar xf gcc.tar

python3 combine.py -f gcc+gm2-master.comb

exit 0

#
#  finally apply the gm2 specific patches to gcc
#

cd gcc
for i in gcc/m2/patches/gcc/trunk/* ; do
    patch -p1 < $i
done

git commit --author="gaius <gaius.mulley@southwales.ac.uk>"  -m "  Applied gm2 patches"
